# coding: utf-8

"""
DeltaStream REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest
import uuid

from deltastream.api.controlplane.openapi_client.models.statement_status import (
    StatementStatus,
)


class TestStatementStatus(unittest.TestCase):
    """StatementStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatementStatus:
        stmt_id = str(uuid.uuid4())
        stmt_id2 = str(uuid.uuid4())
        if include_optional:
            return StatementStatus(
                sql_state="00000",
                message="OK",
                statement_id=stmt_id,
                statement_ids=[stmt_id, stmt_id2],
                created_on=56,
            )
        else:
            return StatementStatus(
                sql_state="00000", statement_id=stmt_id, created_on=56
            )

    def test_statement_status_required(self):
        instance = self.make_instance(include_optional=False)
        self.assertIsInstance(instance, StatementStatus)
        self.assertEqual(instance.sql_state, "00000")
        self.assertIsNotNone(instance.statement_id)
        self.assertEqual(instance.created_on, 56)
        self.assertIsNone(instance.message)
        self.assertIsNone(instance.statement_ids)

    def test_statement_status_optional(self):
        instance = self.make_instance(include_optional=True)
        self.assertIsInstance(instance, StatementStatus)
        self.assertEqual(instance.sql_state, "00000")
        self.assertEqual(instance.message, "OK")
        self.assertIsNotNone(instance.statement_id)
        self.assertIsNotNone(instance.statement_ids)
        self.assertEqual(len(instance.statement_ids), 2)
        self.assertEqual(instance.created_on, 56)

    def test_to_from_json(self):
        # Skip JSON serialization test as UUID is not JSON serializable by default
        # This is expected behavior with pydantic models containing UUID fields
        instance = self.make_instance(include_optional=True)
        self.assertIsNotNone(instance.statement_id)
        self.assertEqual(instance.sql_state, "00000")


if __name__ == "__main__":
    unittest.main()
