# coding: utf-8

"""
DeltaStream REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from deltastream.api.controlplane.openapi_client.models.statement_status import (
    StatementStatus,
)


class TestStatementStatus(unittest.TestCase):
    """StatementStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatementStatus:
        if include_optional:
            return StatementStatus(
                sql_state="00000",
                message="OK",
                statement_id="stmt1",
                statement_ids=["stmt1", "stmt2"],
                created_on=56,
            )
        else:
            return StatementStatus(
                sql_state="00000", statement_id="stmt1", created_on=56
            )

    def test_statement_status_required(self):
        instance = self.make_instance(include_optional=False)
        self.assertIsInstance(instance, StatementStatus)
        self.assertEqual(instance.sql_state, "00000")
        self.assertEqual(instance.statement_id, "stmt1")
        self.assertEqual(instance.created_on, 56)
        self.assertIsNone(instance.message)
        self.assertIsNone(instance.statement_ids)

    def test_statement_status_optional(self):
        instance = self.make_instance(include_optional=True)
        self.assertIsInstance(instance, StatementStatus)
        self.assertEqual(instance.sql_state, "00000")
        self.assertEqual(instance.message, "OK")
        self.assertEqual(instance.statement_id, "stmt1")
        self.assertEqual(instance.statement_ids, ["stmt1", "stmt2"])
        self.assertEqual(instance.created_on, 56)

    def test_to_from_json(self):
        instance = self.make_instance(include_optional=True)
        json_str = instance.to_json()
        new_instance = StatementStatus.from_json(json_str)
        self.assertEqual(instance, new_instance)


if __name__ == "__main__":
    unittest.main()
