# coding: utf-8

"""
DeltaStream REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from deltastream.api.controlplane.openapi_client.models.statement_request_parameters import (
    StatementRequestParameters,
)


class TestStatementRequestParameters(unittest.TestCase):
    """StatementRequestParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatementRequestParameters:
        """Test StatementRequestParameters
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        if include_optional:
            return StatementRequestParameters(
                timezone="America/New_York", session_id=""
            )
        else:
            return StatementRequestParameters()

    def test_statement_request_parameters_required(self):
        instance = self.make_instance(include_optional=False)
        self.assertIsInstance(instance, StatementRequestParameters)
        self.assertIsNone(instance.timezone)
        self.assertIsNone(instance.session_id)

    def test_statement_request_parameters_optional(self):
        instance = self.make_instance(include_optional=True)
        self.assertIsInstance(instance, StatementRequestParameters)
        self.assertEqual(instance.timezone, "America/New_York")
        self.assertEqual(instance.session_id, "")

    def test_to_from_json(self):
        instance = self.make_instance(include_optional=True)
        json_str = instance.to_json()
        new_instance = StatementRequestParameters.from_json(json_str)
        self.assertEqual(instance, new_instance)


if __name__ == "__main__":
    unittest.main()
